layouts_iteration/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :welcome, :users
end

layouts_iteration/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

layouts_iteration/app/models/user.rb
class User < ApplicationRecord
end

layouts_iteration/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

layouts_iteration/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
  end

end

layouts_iteration/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end

  def show

  end

end

layouts_iteration/app/helpers/application_helper.rb
module ApplicationHelper
end

layouts_iteration/app/helpers/users_helper.rb
module UsersHelper
end

layouts_iteration/app/helpers/welcome_helper.rb
module WelcomeHelper
end

layouts_iteration/app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Layouts
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %h1
    = yield

layouts_iteration/app/views/layouts/users.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Layouts
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body.flex
    %h1
    = yield

layouts_iteration/app/views/layouts/welcome.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Layouts
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %h1
    = yield

layouts_iteration/app/views/users/index.html.haml
.content.flex
  - @users.each do |user|
    .personal-info-card.flex
      =image_tag ("#{user.imagepath}"), alt: '', height: '', width: '', class: 'img'
      %h1.itemuserlist.name.font-family.font-placing
        = user.name
      %h3.itemuserlist.occupation.font-family.font-placing
        = user.occupation
      %p.itemuserlist.info.font-family.font-placing
        = user.info
      %p.itemuserlist.button.font-family
        = link_to "Encuéntrame", user, class: 'link'

layouts_iteration/app/views/users/show.html.haml
.personal-info-card.flex
  =image_tag ("#{@user.imagepath}"), alt: '', height: '', width: '', class: 'img'
  %h1.itemuserlist.name.font-family.font-placing
    = @user.name
  %h3.itemuserlist.occupation.font-family.font-placing
    = @user.occupation
  %p.itemuserlist.info.font-family.font-placing
    = @user.info
  %p.itemuserlist.button.font-family
    = link_to "Volver", users_path, class: 'link'

layouts_iteration/app/views/welcome/index.html.haml
%h2
  Estamos en el Yield de Welcome
%h3
  Evaluación de Variable Boolean
- if @ok
  %h3= @its_ok
- else
  %h3= @its_not_ok
- content_for :header do
  %h1 esto se descontrolo
= image_tag 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpW7RyaDF5H20uLza0LORM-dwn1x7MrPNje39drr9rvh5k_6uPtw', alt: '', height: '', width: '', class: ''

.class
  %h1 esto es un div con class